/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek;

import image.DialogLogin;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.security.pkcs11.Secmod;

/**
 *
 * @author eg4n
 */
public class HalamanAdmin extends javax.swing.JFrame {


    /**
     * Creates new form HalamanAdmin
     */
    public database db;
    public apotekTabelModel TApotek;
    public apotekTabelModelK TKaryawan;
    public apotekTabelModelB TBarang;
    
    public HalamanAdmin() {
        
        initComponents();
        fungsi_admin.setText(db.ad);
    }
    
   
   
   
    
    public void refreshData() {
        TApotek.setData(db.tampil_data());
        TApotek.fireTableDataChanged();
        
    }
    public void refreshDataKaryawan() {
        TKaryawan.setData(db.tampil_data_Karyawan());
        TKaryawan.fireTableDataChanged();
    }
    
    public void refreshDataBarang() {
        TBarang.setData(db.tampil_data_barang());
        TBarang.fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane(jPanel2);
        jPanel2 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        db=new database();
        TApotek=new apotekTabelModel();
        TApotek.setData(db.tampil_data());
        tabelApotek = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        db=new database();
        TKaryawan=new apotekTabelModelK();
        TKaryawan.setData(db.tampil_data_Karyawan());
        tabelKaryawan = new javax.swing.JTable();
        btnKtambah = new javax.swing.JButton();
        btnKedit = new javax.swing.JButton();
        btnKdelete = new javax.swing.JButton();
        btnKju = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        db=new database();
        TBarang=new apotekTabelModelB();
        TBarang.setData(db.tampil_data_barang());
        jTable1 = new javax.swing.JTable();
        btnOtambah = new javax.swing.JButton();
        btnOedit = new javax.swing.JButton();
        btnOdelete = new javax.swing.JButton();
        btnOCariO = new javax.swing.JButton();
        btnHistori = new javax.swing.JButton();
        btnOCariO1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fungsi_admin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Control");

        btnTambah.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));

        tabelApotek.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tabelApotek.setModel(TApotek);
        tabelApotek.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tabelApotek);

        jLabel2.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        jLabel2.setText("DAFTAR USER");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon3.png"))); // NOI18N

        javax.swing.GroupLayout btnTambahLayout = new javax.swing.GroupLayout(btnTambah);
        btnTambah.setLayout(btnTambahLayout);
        btnTambahLayout.setHorizontalGroup(
            btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTambahLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnTambahLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2))
                    .addGroup(btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTambahLayout.createSequentialGroup()
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        btnTambahLayout.setVerticalGroup(
            btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTambahLayout.createSequentialGroup()
                .addGroup(btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnTambahLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(255, 255, 255));
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newExit.png"))); // NOI18N
        btnexit.setText("Exit");
        btnexit.setMaximumSize(new java.awt.Dimension(101, 41));
        btnexit.setMinimumSize(new java.awt.Dimension(101, 41));
        btnexit.setPreferredSize(new java.awt.Dimension(101, 41));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Karyawan"));

        jLabel3.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        jLabel3.setText("DAFTAR KARYAWAN");

        tabelKaryawan.setModel(TKaryawan);
        jScrollPane3.setViewportView(tabelKaryawan);

        btnKtambah.setText("Tambah");
        btnKtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKtambahActionPerformed(evt);
            }
        });

        btnKedit.setText("Edit");
        btnKedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeditActionPerformed(evt);
            }
        });

        btnKdelete.setText("Delete");
        btnKdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKdeleteActionPerformed(evt);
            }
        });

        btnKju.setText("Jadikan User");
        btnKju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKjuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(256, 256, 256))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnKtambah, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKedit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKju, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKtambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKedit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKju, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Barang"));

        jLabel4.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        jLabel4.setText("DAFTAR OBAT");

        jTable1.setModel(TBarang);
        jScrollPane4.setViewportView(jTable1);

        btnOtambah.setText("Tambah");
        btnOtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtambahActionPerformed(evt);
            }
        });

        btnOedit.setText("Edit");
        btnOedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOeditActionPerformed(evt);
            }
        });

        btnOdelete.setText("Delete");
        btnOdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdeleteActionPerformed(evt);
            }
        });

        btnOCariO.setText("Cari Obat");
        btnOCariO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOCariOActionPerformed(evt);
            }
        });

        btnHistori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksi.png"))); // NOI18N
        btnHistori.setText("Histori");
        btnHistori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriActionPerformed(evt);
            }
        });

        btnOCariO1.setText("Refresh");
        btnOCariO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOCariO1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnOtambah, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOedit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOCariO1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnHistori)
                                .addGap(38, 38, 38)
                                .addComponent(btnOCariO, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOedit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOCariO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistori, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOCariO1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jLabel5.setText("Admin aktif : ");

        fungsi_admin.setText("fungsi_admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(btnlogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fungsi_admin)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 123, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fungsi_admin))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnlogout)
                            .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1428, 1148));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    DialogTambah t;    DialogEdit edit;
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            edit = new DialogEdit(this, true);
            int baris=tabelApotek.getSelectedRow();
      
            int id=(Integer) tabelApotek.getValueAt(baris, 0);
            apotek_a a = db.pilih_1_user(id);
            if(a!=null) {
                edit.setForm(a);
                edit.setVisible(true);
                refreshData();
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di edit!","Error",JOptionPane.INFORMATION_MESSAGE);
        
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       db = new database();
        try {
            
            int baris = tabelApotek.getSelectedRow();
            int id = (Integer) tabelApotek.getValueAt(baris, 0);
            String user = (String) tabelApotek.getValueAt(baris, 2);
            Object[] pilihan={"ya","Tidak"};
            int jawaban= JOptionPane.showOptionDialog(null,"Apakah anda yakin akan menhapus user "+user+"?", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, pilihan, pilihan[0]);
            if(jawaban ==0) {
                try {
                    db.hapus_user(id);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
                    refreshData();
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di hapus!","Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        login l = new login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    DialogTambahUser Tuser;
    private void btnKjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKjuActionPerformed
        // TODO add your handling code here:
         try {
            Tuser = new DialogTambahUser(this, true);
            int baris=tabelKaryawan.getSelectedRow();
      
            String id=(String) tabelKaryawan.getValueAt(baris, 0);
            apotek_k a = db.pilih_1_karyawan(id);
            if(a!=null) {
                Tuser.setForm(a);
                Tuser.setVisible(true);
                refreshData();
                refreshDataKaryawan();
                
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data karyawan yang akan dijadikan user!","Error",JOptionPane.INFORMATION_MESSAGE);
        
        }
    }//GEN-LAST:event_btnKjuActionPerformed

    private void btnKdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKdeleteActionPerformed
        // TODO add your handling code here:
        db = new database();
        try {
            
            int baris = tabelKaryawan.getSelectedRow();
            String id = (String) tabelKaryawan.getValueAt(baris, 0);
            String nama = (String) tabelKaryawan.getValueAt(baris, 1);
            Object[] pilihan={"ya","Tidak"};
            int jawaban= JOptionPane.showOptionDialog(null,"Apakah anda yakin akan menhapus data karyawan dengan nama "+nama+"?", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, pilihan, pilihan[0]);
            if(jawaban ==0) {
                try {
                    db.hapus_karyawan(id);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
                    refreshDataKaryawan();
                    refreshData();
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di hapus!","Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnKdeleteActionPerformed
    
    DialogEditKaryawan editK;
    private void btnKeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeditActionPerformed
        // TODO add your handling code here:
         try {
            editK = new DialogEditKaryawan(this, true);
            int baris=tabelKaryawan.getSelectedRow();
      
            String id=(String) tabelKaryawan.getValueAt(baris, 0);
            apotek_k a = db.pilih_1_karyawan(id);
            if(a!=null) {
                editK.setForm(a);
                editK.setVisible(true);
                refreshDataKaryawan();
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di edit!","Error",JOptionPane.INFORMATION_MESSAGE);
        
        }
    }//GEN-LAST:event_btnKeditActionPerformed

    private void btnKtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKtambahActionPerformed
        // TODO add your handling code here:
        t = new DialogTambah(this, true);
        t.setVisible(true);
        refreshDataKaryawan();

    }//GEN-LAST:event_btnKtambahActionPerformed
    DialogTambahBarang b;
    private void btnOtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtambahActionPerformed
        // TODO add your handling code here:
        try {
            b = new DialogTambahBarang(this, true);
            b.setVisible(true);
            refreshDataBarang();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"ada kesalahan input,Tolong di periksa kembali!");
        }
    }//GEN-LAST:event_btnOtambahActionPerformed
    
    DialogEditBarang editB;
    private void btnOeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOeditActionPerformed
        // TODO add your handling code here:
        try {
            editB = new DialogEditBarang(this, true);
            int baris=jTable1.getSelectedRow();
      
            String id=(String) jTable1.getValueAt(baris, 0);
            apotek_o a = db.pilih_1_barang(id);
            if(a!=null) {
                editB.setForm(a);
                editB.setVisible(true);
                refreshDataBarang();
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di edit!","Error",JOptionPane.INFORMATION_MESSAGE);
        
        }
    }//GEN-LAST:event_btnOeditActionPerformed

    private void btnOdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdeleteActionPerformed
        // TODO add your handling code here:
        db = new database();
        try {
            
            int baris = jTable1.getSelectedRow();
            String id = (String) jTable1.getValueAt(baris, 0);
            String nama = (String) jTable1.getValueAt(baris, 1);
            Object[] pilihan={"ya","Tidak"};
            int jawaban= JOptionPane.showOptionDialog(null,"Apakah anda yakin akan menghapus data obat "+nama+"?", "Warning", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, pilihan, pilihan[0]);
            if(jawaban ==0) {
                try {
                    db.hapus_barang(id);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(HalamanAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
                    refreshDataBarang();
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di hapus!","Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnOdeleteActionPerformed

    private void btnOCariOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOCariOActionPerformed
        // TODO add your handling code here:
       try {
        caei_barang c = new caei_barang(this, true);
        c.setVisible(true);
        if ("id".equals(c.getCari())) {
            TBarang.setData(db.filter_Barang_id(c.getKunci()));
        } else if("nama".equals(c.getCari())){
             TBarang.setData(db.filter_Barang_nama(c.getKunci()));
        } else if ("suplier".equals(c.getCari())) {
            TBarang.setData(db.filter_Barang_suplier(c.getKunci()));
        }
        
        TBarang.fireTableDataChanged();
       } catch (Exception e) {
           System.out.print(e.getMessage());
       }
    }//GEN-LAST:event_btnOCariOActionPerformed

    private void btnHistoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriActionPerformed
        // TODO add your handling code here:
        DialogLogBarang log = new DialogLogBarang(this, true);
        log.setVisible(true);


    }//GEN-LAST:event_btnHistoriActionPerformed

    private void btnOCariO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOCariO1ActionPerformed
        // TODO add your handling code here:
        refreshDataBarang();
    }//GEN-LAST:event_btnOCariO1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanAdmin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHistori;
    private javax.swing.JButton btnKdelete;
    private javax.swing.JButton btnKedit;
    private javax.swing.JButton btnKju;
    private javax.swing.JButton btnKtambah;
    private javax.swing.JButton btnOCariO;
    private javax.swing.JButton btnOCariO1;
    private javax.swing.JButton btnOdelete;
    private javax.swing.JButton btnOedit;
    private javax.swing.JButton btnOtambah;
    private javax.swing.JPanel btnTambah;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel fungsi_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelApotek;
    private javax.swing.JTable tabelKaryawan;
    // End of variables declaration//GEN-END:variables
}
